### ISSUE TITLE
What's the difference between "certify_noapproximate" and "certify"?

### ISSUE THREAD

**Issue by huanranchen** [Jayfeather1024/DensePure#1]
Hi!
   Thanks for such great work and your code. In core.py, there are two functions, "certify_noapproximate" and "certify". "certify_noapproximate" seems more likely the implementation in Randomized Smoothing, so why do you use "certify" instead of "certify_noapproximate"?

**Comment by Jayfeather1024** [comment]
hi, "certify_noapproximate" computes the certified radius from euqation (3) in paper [1], where you need to compute both p_a and p_b. The "certify" one uses 1-p_a to estimate p_b. You can refer to Section 3.2.2 for the details of the difference. The implementation in Randomized Smoothing in fact just uses the "certify" one.

[1] Cohen, Jeremy, Elan Rosenfeld, and Zico Kolter. Certified adversarial robustness via randomized smoothing. international conference on machine learning. PMLR, 2019.

**Comment by huanranchen** [comment]
> hi, "certify_noapproximate" computes the certified radius from euqation (3) in paper [1], where you need to compute both p_a and p_b. The "certify" one uses 1-p_a to estimate p_b. You can refer to Section 3.2.2 for the details of the difference. The implementation in Randomized Smoothing in fact just uses the "certify" one.
> 
> [1] Cohen, Jeremy, Elan Rosenfeld, and Zico Kolter. Certified adversarial robustness via randomized smoothing. international conference on machine learning. PMLR, 2019.

Hi! I still have a question about this topic.

From my perspective, the "certify" method utilizes 1-p_a to estimate p_b, which is more efficient since it doesn't necessitate the computation of lower confidence bounds for all classes. In contrast, the "certify_noapproximate" approach calculates the lower confidence bound for every class and selects the maximum value as p_b. Consequently, it incurs higher computational costs **but yields better certified robustness** due to the fact that p_b is smaller than the one obtained using the "certify" method.

Could you kindly confirm if my understanding is correct?

**Comment by Jayfeather1024** [comment]
Your understanding is correct. We finally use the "certify" function instead of "certify_noapproximate" because "certify" function is used in baseline methods for fair comparison.

**Comment by huanranchen** [comment]
Thank you~

> Your understanding is correct. We finally use the "certify" function instead of "certify_noapproximate" because "certify" function is used in baseline methods for fair comparison.
